// Generated by jextract

package io.vacco.ujgl.gfx.glfw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class glfw3_h extends glfw3_h_1 {

    glfw3_h() {
        // Should not be called directly
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_RAY_TRACING_LINEAR_SWEPT_SPHERES_EXTENSION_NAME "VK_NV_ray_tracing_linear_swept_spheres"
     * }
     */
    public static MemorySegment VK_NV_RAY_TRACING_LINEAR_SWEPT_SPHERES_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_RAY_TRACING_LINEAR_SWEPT_SPHERES_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_ray_tracing_linear_swept_spheres");
        }
        return Holder.VK_NV_RAY_TRACING_LINEAR_SWEPT_SPHERES_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_LINEAR_COLOR_ATTACHMENT_EXTENSION_NAME "VK_NV_linear_color_attachment"
     * }
     */
    public static MemorySegment VK_NV_LINEAR_COLOR_ATTACHMENT_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_LINEAR_COLOR_ATTACHMENT_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_linear_color_attachment");
        }
        return Holder.VK_NV_LINEAR_COLOR_ATTACHMENT_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_GOOGLE_SURFACELESS_QUERY_EXTENSION_NAME "VK_GOOGLE_surfaceless_query"
     * }
     */
    public static MemorySegment VK_GOOGLE_SURFACELESS_QUERY_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_GOOGLE_SURFACELESS_QUERY_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_GOOGLE_surfaceless_query");
        }
        return Holder.VK_GOOGLE_SURFACELESS_QUERY_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_IMAGE_COMPRESSION_CONTROL_SWAPCHAIN_EXTENSION_NAME "VK_EXT_image_compression_control_swapchain"
     * }
     */
    public static MemorySegment VK_EXT_IMAGE_COMPRESSION_CONTROL_SWAPCHAIN_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_IMAGE_COMPRESSION_CONTROL_SWAPCHAIN_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_image_compression_control_swapchain");
        }
        return Holder.VK_EXT_IMAGE_COMPRESSION_CONTROL_SWAPCHAIN_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_QCOM_IMAGE_PROCESSING_EXTENSION_NAME "VK_QCOM_image_processing"
     * }
     */
    public static MemorySegment VK_QCOM_IMAGE_PROCESSING_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_QCOM_IMAGE_PROCESSING_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_QCOM_image_processing");
        }
        return Holder.VK_QCOM_IMAGE_PROCESSING_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_NESTED_COMMAND_BUFFER_EXTENSION_NAME "VK_EXT_nested_command_buffer"
     * }
     */
    public static MemorySegment VK_EXT_NESTED_COMMAND_BUFFER_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_NESTED_COMMAND_BUFFER_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_nested_command_buffer");
        }
        return Holder.VK_EXT_NESTED_COMMAND_BUFFER_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_EXTERNAL_MEMORY_ACQUIRE_UNMODIFIED_EXTENSION_NAME "VK_EXT_external_memory_acquire_unmodified"
     * }
     */
    public static MemorySegment VK_EXT_EXTERNAL_MEMORY_ACQUIRE_UNMODIFIED_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_EXTERNAL_MEMORY_ACQUIRE_UNMODIFIED_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_external_memory_acquire_unmodified");
        }
        return Holder.VK_EXT_EXTERNAL_MEMORY_ACQUIRE_UNMODIFIED_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_EXTENDED_DYNAMIC_STATE_3_EXTENSION_NAME "VK_EXT_extended_dynamic_state3"
     * }
     */
    public static MemorySegment VK_EXT_EXTENDED_DYNAMIC_STATE_3_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_EXTENDED_DYNAMIC_STATE_3_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_extended_dynamic_state3");
        }
        return Holder.VK_EXT_EXTENDED_DYNAMIC_STATE_3_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SUBPASS_MERGE_FEEDBACK_EXTENSION_NAME "VK_EXT_subpass_merge_feedback"
     * }
     */
    public static MemorySegment VK_EXT_SUBPASS_MERGE_FEEDBACK_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SUBPASS_MERGE_FEEDBACK_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_subpass_merge_feedback");
        }
        return Holder.VK_EXT_SUBPASS_MERGE_FEEDBACK_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_LUNARG_DIRECT_DRIVER_LOADING_EXTENSION_NAME "VK_LUNARG_direct_driver_loading"
     * }
     */
    public static MemorySegment VK_LUNARG_DIRECT_DRIVER_LOADING_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_LUNARG_DIRECT_DRIVER_LOADING_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_LUNARG_direct_driver_loading");
        }
        return Holder.VK_LUNARG_DIRECT_DRIVER_LOADING_EXTENSION_NAME;
    }
    private static final int VK_MAX_SHADER_MODULE_IDENTIFIER_SIZE_EXT = (int)32L;
    /**
     * {@snippet lang=c :
     * #define VK_MAX_SHADER_MODULE_IDENTIFIER_SIZE_EXT 32
     * }
     */
    public static int VK_MAX_SHADER_MODULE_IDENTIFIER_SIZE_EXT() {
        return VK_MAX_SHADER_MODULE_IDENTIFIER_SIZE_EXT;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SHADER_MODULE_IDENTIFIER_EXTENSION_NAME "VK_EXT_shader_module_identifier"
     * }
     */
    public static MemorySegment VK_EXT_SHADER_MODULE_IDENTIFIER_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SHADER_MODULE_IDENTIFIER_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_shader_module_identifier");
        }
        return Holder.VK_EXT_SHADER_MODULE_IDENTIFIER_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_EXTENSION_NAME "VK_EXT_rasterization_order_attachment_access"
     * }
     */
    public static MemorySegment VK_EXT_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_rasterization_order_attachment_access");
        }
        return Holder.VK_EXT_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_OPTICAL_FLOW_EXTENSION_NAME "VK_NV_optical_flow"
     * }
     */
    public static MemorySegment VK_NV_OPTICAL_FLOW_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_OPTICAL_FLOW_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_optical_flow");
        }
        return Holder.VK_NV_OPTICAL_FLOW_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_LEGACY_DITHERING_EXTENSION_NAME "VK_EXT_legacy_dithering"
     * }
     */
    public static MemorySegment VK_EXT_LEGACY_DITHERING_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_LEGACY_DITHERING_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_legacy_dithering");
        }
        return Holder.VK_EXT_LEGACY_DITHERING_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_PIPELINE_PROTECTED_ACCESS_EXTENSION_NAME "VK_EXT_pipeline_protected_access"
     * }
     */
    public static MemorySegment VK_EXT_PIPELINE_PROTECTED_ACCESS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_PIPELINE_PROTECTED_ACCESS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_pipeline_protected_access");
        }
        return Holder.VK_EXT_PIPELINE_PROTECTED_ACCESS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_AMD_ANTI_LAG_EXTENSION_NAME "VK_AMD_anti_lag"
     * }
     */
    public static MemorySegment VK_AMD_ANTI_LAG_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_AMD_ANTI_LAG_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_AMD_anti_lag");
        }
        return Holder.VK_AMD_ANTI_LAG_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SHADER_OBJECT_EXTENSION_NAME "VK_EXT_shader_object"
     * }
     */
    public static MemorySegment VK_EXT_SHADER_OBJECT_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SHADER_OBJECT_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_shader_object");
        }
        return Holder.VK_EXT_SHADER_OBJECT_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_QCOM_TILE_PROPERTIES_EXTENSION_NAME "VK_QCOM_tile_properties"
     * }
     */
    public static MemorySegment VK_QCOM_TILE_PROPERTIES_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_QCOM_TILE_PROPERTIES_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_QCOM_tile_properties");
        }
        return Holder.VK_QCOM_TILE_PROPERTIES_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_SEC_AMIGO_PROFILING_EXTENSION_NAME "VK_SEC_amigo_profiling"
     * }
     */
    public static MemorySegment VK_SEC_AMIGO_PROFILING_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_SEC_AMIGO_PROFILING_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_SEC_amigo_profiling");
        }
        return Holder.VK_SEC_AMIGO_PROFILING_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_QCOM_MULTIVIEW_PER_VIEW_VIEWPORTS_EXTENSION_NAME "VK_QCOM_multiview_per_view_viewports"
     * }
     */
    public static MemorySegment VK_QCOM_MULTIVIEW_PER_VIEW_VIEWPORTS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_QCOM_MULTIVIEW_PER_VIEW_VIEWPORTS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_QCOM_multiview_per_view_viewports");
        }
        return Holder.VK_QCOM_MULTIVIEW_PER_VIEW_VIEWPORTS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_RAY_TRACING_INVOCATION_REORDER_EXTENSION_NAME "VK_NV_ray_tracing_invocation_reorder"
     * }
     */
    public static MemorySegment VK_NV_RAY_TRACING_INVOCATION_REORDER_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_RAY_TRACING_INVOCATION_REORDER_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_ray_tracing_invocation_reorder");
        }
        return Holder.VK_NV_RAY_TRACING_INVOCATION_REORDER_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_COOPERATIVE_VECTOR_EXTENSION_NAME "VK_NV_cooperative_vector"
     * }
     */
    public static MemorySegment VK_NV_COOPERATIVE_VECTOR_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_COOPERATIVE_VECTOR_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_cooperative_vector");
        }
        return Holder.VK_NV_COOPERATIVE_VECTOR_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_EXTENDED_SPARSE_ADDRESS_SPACE_EXTENSION_NAME "VK_NV_extended_sparse_address_space"
     * }
     */
    public static MemorySegment VK_NV_EXTENDED_SPARSE_ADDRESS_SPACE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_EXTENDED_SPARSE_ADDRESS_SPACE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_extended_sparse_address_space");
        }
        return Holder.VK_NV_EXTENDED_SPARSE_ADDRESS_SPACE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_MUTABLE_DESCRIPTOR_TYPE_EXTENSION_NAME "VK_EXT_mutable_descriptor_type"
     * }
     */
    public static MemorySegment VK_EXT_MUTABLE_DESCRIPTOR_TYPE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_MUTABLE_DESCRIPTOR_TYPE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_mutable_descriptor_type");
        }
        return Holder.VK_EXT_MUTABLE_DESCRIPTOR_TYPE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_LEGACY_VERTEX_ATTRIBUTES_EXTENSION_NAME "VK_EXT_legacy_vertex_attributes"
     * }
     */
    public static MemorySegment VK_EXT_LEGACY_VERTEX_ATTRIBUTES_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_LEGACY_VERTEX_ATTRIBUTES_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_legacy_vertex_attributes");
        }
        return Holder.VK_EXT_LEGACY_VERTEX_ATTRIBUTES_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_LAYER_SETTINGS_EXTENSION_NAME "VK_EXT_layer_settings"
     * }
     */
    public static MemorySegment VK_EXT_LAYER_SETTINGS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_LAYER_SETTINGS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_layer_settings");
        }
        return Holder.VK_EXT_LAYER_SETTINGS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_ARM_SHADER_CORE_BUILTINS_EXTENSION_NAME "VK_ARM_shader_core_builtins"
     * }
     */
    public static MemorySegment VK_ARM_SHADER_CORE_BUILTINS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_ARM_SHADER_CORE_BUILTINS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_ARM_shader_core_builtins");
        }
        return Holder.VK_ARM_SHADER_CORE_BUILTINS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_PIPELINE_LIBRARY_GROUP_HANDLES_EXTENSION_NAME "VK_EXT_pipeline_library_group_handles"
     * }
     */
    public static MemorySegment VK_EXT_PIPELINE_LIBRARY_GROUP_HANDLES_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_PIPELINE_LIBRARY_GROUP_HANDLES_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_pipeline_library_group_handles");
        }
        return Holder.VK_EXT_PIPELINE_LIBRARY_GROUP_HANDLES_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_DYNAMIC_RENDERING_UNUSED_ATTACHMENTS_EXTENSION_NAME "VK_EXT_dynamic_rendering_unused_attachments"
     * }
     */
    public static MemorySegment VK_EXT_DYNAMIC_RENDERING_UNUSED_ATTACHMENTS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_DYNAMIC_RENDERING_UNUSED_ATTACHMENTS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_dynamic_rendering_unused_attachments");
        }
        return Holder.VK_EXT_DYNAMIC_RENDERING_UNUSED_ATTACHMENTS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_LOW_LATENCY_2_EXTENSION_NAME "VK_NV_low_latency2"
     * }
     */
    public static MemorySegment VK_NV_LOW_LATENCY_2_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_LOW_LATENCY_2_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_low_latency2");
        }
        return Holder.VK_NV_LOW_LATENCY_2_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_QCOM_MULTIVIEW_PER_VIEW_RENDER_AREAS_EXTENSION_NAME "VK_QCOM_multiview_per_view_render_areas"
     * }
     */
    public static MemorySegment VK_QCOM_MULTIVIEW_PER_VIEW_RENDER_AREAS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_QCOM_MULTIVIEW_PER_VIEW_RENDER_AREAS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_QCOM_multiview_per_view_render_areas");
        }
        return Holder.VK_QCOM_MULTIVIEW_PER_VIEW_RENDER_AREAS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_PER_STAGE_DESCRIPTOR_SET_EXTENSION_NAME "VK_NV_per_stage_descriptor_set"
     * }
     */
    public static MemorySegment VK_NV_PER_STAGE_DESCRIPTOR_SET_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_PER_STAGE_DESCRIPTOR_SET_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_per_stage_descriptor_set");
        }
        return Holder.VK_NV_PER_STAGE_DESCRIPTOR_SET_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_QCOM_IMAGE_PROCESSING_2_EXTENSION_NAME "VK_QCOM_image_processing2"
     * }
     */
    public static MemorySegment VK_QCOM_IMAGE_PROCESSING_2_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_QCOM_IMAGE_PROCESSING_2_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_QCOM_image_processing2");
        }
        return Holder.VK_QCOM_IMAGE_PROCESSING_2_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_QCOM_FILTER_CUBIC_WEIGHTS_EXTENSION_NAME "VK_QCOM_filter_cubic_weights"
     * }
     */
    public static MemorySegment VK_QCOM_FILTER_CUBIC_WEIGHTS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_QCOM_FILTER_CUBIC_WEIGHTS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_QCOM_filter_cubic_weights");
        }
        return Holder.VK_QCOM_FILTER_CUBIC_WEIGHTS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_QCOM_YCBCR_DEGAMMA_EXTENSION_NAME "VK_QCOM_ycbcr_degamma"
     * }
     */
    public static MemorySegment VK_QCOM_YCBCR_DEGAMMA_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_QCOM_YCBCR_DEGAMMA_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_QCOM_ycbcr_degamma");
        }
        return Holder.VK_QCOM_YCBCR_DEGAMMA_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_QCOM_FILTER_CUBIC_CLAMP_EXTENSION_NAME "VK_QCOM_filter_cubic_clamp"
     * }
     */
    public static MemorySegment VK_QCOM_FILTER_CUBIC_CLAMP_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_QCOM_FILTER_CUBIC_CLAMP_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_QCOM_filter_cubic_clamp");
        }
        return Holder.VK_QCOM_FILTER_CUBIC_CLAMP_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_ATTACHMENT_FEEDBACK_LOOP_DYNAMIC_STATE_EXTENSION_NAME "VK_EXT_attachment_feedback_loop_dynamic_state"
     * }
     */
    public static MemorySegment VK_EXT_ATTACHMENT_FEEDBACK_LOOP_DYNAMIC_STATE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_ATTACHMENT_FEEDBACK_LOOP_DYNAMIC_STATE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_attachment_feedback_loop_dynamic_state");
        }
        return Holder.VK_EXT_ATTACHMENT_FEEDBACK_LOOP_DYNAMIC_STATE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_MSFT_LAYERED_DRIVER_EXTENSION_NAME "VK_MSFT_layered_driver"
     * }
     */
    public static MemorySegment VK_MSFT_LAYERED_DRIVER_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_MSFT_LAYERED_DRIVER_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_MSFT_layered_driver");
        }
        return Holder.VK_MSFT_LAYERED_DRIVER_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_DESCRIPTOR_POOL_OVERALLOCATION_EXTENSION_NAME "VK_NV_descriptor_pool_overallocation"
     * }
     */
    public static MemorySegment VK_NV_DESCRIPTOR_POOL_OVERALLOCATION_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_DESCRIPTOR_POOL_OVERALLOCATION_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_descriptor_pool_overallocation");
        }
        return Holder.VK_NV_DESCRIPTOR_POOL_OVERALLOCATION_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_DISPLAY_STEREO_EXTENSION_NAME "VK_NV_display_stereo"
     * }
     */
    public static MemorySegment VK_NV_DISPLAY_STEREO_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_DISPLAY_STEREO_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_display_stereo");
        }
        return Holder.VK_NV_DISPLAY_STEREO_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_RAW_ACCESS_CHAINS_EXTENSION_NAME "VK_NV_raw_access_chains"
     * }
     */
    public static MemorySegment VK_NV_RAW_ACCESS_CHAINS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_RAW_ACCESS_CHAINS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_raw_access_chains");
        }
        return Holder.VK_NV_RAW_ACCESS_CHAINS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_COMMAND_BUFFER_INHERITANCE_EXTENSION_NAME "VK_NV_command_buffer_inheritance"
     * }
     */
    public static MemorySegment VK_NV_COMMAND_BUFFER_INHERITANCE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_COMMAND_BUFFER_INHERITANCE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_command_buffer_inheritance");
        }
        return Holder.VK_NV_COMMAND_BUFFER_INHERITANCE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_SHADER_ATOMIC_FLOAT16_VECTOR_EXTENSION_NAME "VK_NV_shader_atomic_float16_vector"
     * }
     */
    public static MemorySegment VK_NV_SHADER_ATOMIC_FLOAT16_VECTOR_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_SHADER_ATOMIC_FLOAT16_VECTOR_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_shader_atomic_float16_vector");
        }
        return Holder.VK_NV_SHADER_ATOMIC_FLOAT16_VECTOR_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SHADER_REPLICATED_COMPOSITES_EXTENSION_NAME "VK_EXT_shader_replicated_composites"
     * }
     */
    public static MemorySegment VK_EXT_SHADER_REPLICATED_COMPOSITES_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SHADER_REPLICATED_COMPOSITES_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_shader_replicated_composites");
        }
        return Holder.VK_EXT_SHADER_REPLICATED_COMPOSITES_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_RAY_TRACING_VALIDATION_EXTENSION_NAME "VK_NV_ray_tracing_validation"
     * }
     */
    public static MemorySegment VK_NV_RAY_TRACING_VALIDATION_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_RAY_TRACING_VALIDATION_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_ray_tracing_validation");
        }
        return Holder.VK_NV_RAY_TRACING_VALIDATION_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_CLUSTER_ACCELERATION_STRUCTURE_EXTENSION_NAME "VK_NV_cluster_acceleration_structure"
     * }
     */
    public static MemorySegment VK_NV_CLUSTER_ACCELERATION_STRUCTURE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_CLUSTER_ACCELERATION_STRUCTURE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_cluster_acceleration_structure");
        }
        return Holder.VK_NV_CLUSTER_ACCELERATION_STRUCTURE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_PARTITIONED_ACCELERATION_STRUCTURE_EXTENSION_NAME "VK_NV_partitioned_acceleration_structure"
     * }
     */
    public static MemorySegment VK_NV_PARTITIONED_ACCELERATION_STRUCTURE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_PARTITIONED_ACCELERATION_STRUCTURE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_partitioned_acceleration_structure");
        }
        return Holder.VK_NV_PARTITIONED_ACCELERATION_STRUCTURE_EXTENSION_NAME;
    }
    private static final int VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV 4294967295
     * }
     */
    public static int VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV() {
        return VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME "VK_EXT_device_generated_commands"
     * }
     */
    public static MemorySegment VK_EXT_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_device_generated_commands");
        }
        return Holder.VK_EXT_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_MESA_IMAGE_ALIGNMENT_CONTROL_EXTENSION_NAME "VK_MESA_image_alignment_control"
     * }
     */
    public static MemorySegment VK_MESA_IMAGE_ALIGNMENT_CONTROL_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_MESA_IMAGE_ALIGNMENT_CONTROL_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_MESA_image_alignment_control");
        }
        return Holder.VK_MESA_IMAGE_ALIGNMENT_CONTROL_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_DEPTH_CLAMP_CONTROL_EXTENSION_NAME "VK_EXT_depth_clamp_control"
     * }
     */
    public static MemorySegment VK_EXT_DEPTH_CLAMP_CONTROL_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_DEPTH_CLAMP_CONTROL_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_depth_clamp_control");
        }
        return Holder.VK_EXT_DEPTH_CLAMP_CONTROL_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_HUAWEI_HDR_VIVID_EXTENSION_NAME "VK_HUAWEI_hdr_vivid"
     * }
     */
    public static MemorySegment VK_HUAWEI_HDR_VIVID_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_HUAWEI_HDR_VIVID_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_HUAWEI_hdr_vivid");
        }
        return Holder.VK_HUAWEI_HDR_VIVID_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_COOPERATIVE_MATRIX_2_EXTENSION_NAME "VK_NV_cooperative_matrix2"
     * }
     */
    public static MemorySegment VK_NV_COOPERATIVE_MATRIX_2_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_COOPERATIVE_MATRIX_2_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_cooperative_matrix2");
        }
        return Holder.VK_NV_COOPERATIVE_MATRIX_2_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_ARM_PIPELINE_OPACITY_MICROMAP_EXTENSION_NAME "VK_ARM_pipeline_opacity_micromap"
     * }
     */
    public static MemorySegment VK_ARM_PIPELINE_OPACITY_MICROMAP_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_ARM_PIPELINE_OPACITY_MICROMAP_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_ARM_pipeline_opacity_micromap");
        }
        return Holder.VK_ARM_PIPELINE_OPACITY_MICROMAP_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_VERTEX_ATTRIBUTE_ROBUSTNESS_EXTENSION_NAME "VK_EXT_vertex_attribute_robustness"
     * }
     */
    public static MemorySegment VK_EXT_VERTEX_ATTRIBUTE_ROBUSTNESS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_VERTEX_ATTRIBUTE_ROBUSTNESS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_vertex_attribute_robustness");
        }
        return Holder.VK_EXT_VERTEX_ATTRIBUTE_ROBUSTNESS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_PRESENT_METERING_EXTENSION_NAME "VK_NV_present_metering"
     * }
     */
    public static MemorySegment VK_NV_PRESENT_METERING_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_PRESENT_METERING_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_present_metering");
        }
        return Holder.VK_NV_PRESENT_METERING_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME "VK_KHR_acceleration_structure"
     * }
     */
    public static MemorySegment VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_KHR_acceleration_structure");
        }
        return Holder.VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME "VK_KHR_ray_tracing_pipeline"
     * }
     */
    public static MemorySegment VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_KHR_ray_tracing_pipeline");
        }
        return Holder.VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_KHR_RAY_QUERY_EXTENSION_NAME "VK_KHR_ray_query"
     * }
     */
    public static MemorySegment VK_KHR_RAY_QUERY_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_KHR_RAY_QUERY_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_KHR_ray_query");
        }
        return Holder.VK_KHR_RAY_QUERY_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_MESH_SHADER_EXTENSION_NAME "VK_EXT_mesh_shader"
     * }
     */
    public static MemorySegment VK_EXT_MESH_SHADER_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_MESH_SHADER_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_mesh_shader");
        }
        return Holder.VK_EXT_MESH_SHADER_EXTENSION_NAME;
    }
    private static final int GL_ALL_ATTRIB_BITS = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_ALL_ATTRIB_BITS 4294967295
     * }
     */
    public static int GL_ALL_ATTRIB_BITS() {
        return GL_ALL_ATTRIB_BITS;
    }
    private static final int GL_ALL_CLIENT_ATTRIB_BITS = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_ALL_CLIENT_ATTRIB_BITS 4294967295
     * }
     */
    public static int GL_ALL_CLIENT_ATTRIB_BITS() {
        return GL_ALL_CLIENT_ATTRIB_BITS;
    }
    private static final int GL_CLIENT_ALL_ATTRIB_BITS = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_CLIENT_ALL_ATTRIB_BITS 4294967295
     * }
     */
    public static int GL_CLIENT_ALL_ATTRIB_BITS() {
        return GL_CLIENT_ALL_ATTRIB_BITS;
    }
    private static final int GL_INVALID_INDEX = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_INVALID_INDEX 4294967295
     * }
     */
    public static int GL_INVALID_INDEX() {
        return GL_INVALID_INDEX;
    }
    private static final long GL_TIMEOUT_IGNORED = -1L;
    /**
     * {@snippet lang=c :
     * #define GL_TIMEOUT_IGNORED -1
     * }
     */
    public static long GL_TIMEOUT_IGNORED() {
        return GL_TIMEOUT_IGNORED;
    }
    private static final int GL_ALL_SHADER_BITS = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_ALL_SHADER_BITS 4294967295
     * }
     */
    public static int GL_ALL_SHADER_BITS() {
        return GL_ALL_SHADER_BITS;
    }
    private static final int GL_ALL_BARRIER_BITS = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_ALL_BARRIER_BITS 4294967295
     * }
     */
    public static int GL_ALL_BARRIER_BITS() {
        return GL_ALL_BARRIER_BITS;
    }
    private static final int GL_ALL_PIXELS_AMD = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_ALL_PIXELS_AMD 4294967295
     * }
     */
    public static int GL_ALL_PIXELS_AMD() {
        return GL_ALL_PIXELS_AMD;
    }
    private static final int GL_QUERY_ALL_EVENT_BITS_AMD = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_QUERY_ALL_EVENT_BITS_AMD 4294967295
     * }
     */
    public static int GL_QUERY_ALL_EVENT_BITS_AMD() {
        return GL_QUERY_ALL_EVENT_BITS_AMD;
    }
    private static final int GL_ALL_BARRIER_BITS_EXT = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_ALL_BARRIER_BITS_EXT 4294967295
     * }
     */
    public static int GL_ALL_BARRIER_BITS_EXT() {
        return GL_ALL_BARRIER_BITS_EXT;
    }
    private static final int GL_NEXT_BUFFER_NV = (int)-2L;
    /**
     * {@snippet lang=c :
     * #define GL_NEXT_BUFFER_NV -2
     * }
     */
    public static int GL_NEXT_BUFFER_NV() {
        return GL_NEXT_BUFFER_NV;
    }
    private static final int GL_SKIP_COMPONENTS4_NV = (int)-3L;
    /**
     * {@snippet lang=c :
     * #define GL_SKIP_COMPONENTS4_NV -3
     * }
     */
    public static int GL_SKIP_COMPONENTS4_NV() {
        return GL_SKIP_COMPONENTS4_NV;
    }
    private static final int GL_SKIP_COMPONENTS3_NV = (int)-4L;
    /**
     * {@snippet lang=c :
     * #define GL_SKIP_COMPONENTS3_NV -4
     * }
     */
    public static int GL_SKIP_COMPONENTS3_NV() {
        return GL_SKIP_COMPONENTS3_NV;
    }
    private static final int GL_SKIP_COMPONENTS2_NV = (int)-5L;
    /**
     * {@snippet lang=c :
     * #define GL_SKIP_COMPONENTS2_NV -5
     * }
     */
    public static int GL_SKIP_COMPONENTS2_NV() {
        return GL_SKIP_COMPONENTS2_NV;
    }
    private static final int GL_SKIP_COMPONENTS1_NV = (int)-6L;
    /**
     * {@snippet lang=c :
     * #define GL_SKIP_COMPONENTS1_NV -6
     * }
     */
    public static int GL_SKIP_COMPONENTS1_NV() {
        return GL_SKIP_COMPONENTS1_NV;
    }
    private static final int GL_TEXCOORD4_BIT_PGI = (int)2147483648L;
    /**
     * {@snippet lang=c :
     * #define GL_TEXCOORD4_BIT_PGI 2147483648
     * }
     */
    public static int GL_TEXCOORD4_BIT_PGI() {
        return GL_TEXCOORD4_BIT_PGI;
    }
    private static final int GLFW_HAT_RIGHT_UP = (int)3L;
    /**
     * {@snippet lang=c :
     * #define GLFW_HAT_RIGHT_UP 3
     * }
     */
    public static int GLFW_HAT_RIGHT_UP() {
        return GLFW_HAT_RIGHT_UP;
    }
    private static final int GLFW_HAT_RIGHT_DOWN = (int)6L;
    /**
     * {@snippet lang=c :
     * #define GLFW_HAT_RIGHT_DOWN 6
     * }
     */
    public static int GLFW_HAT_RIGHT_DOWN() {
        return GLFW_HAT_RIGHT_DOWN;
    }
    private static final int GLFW_HAT_LEFT_UP = (int)9L;
    /**
     * {@snippet lang=c :
     * #define GLFW_HAT_LEFT_UP 9
     * }
     */
    public static int GLFW_HAT_LEFT_UP() {
        return GLFW_HAT_LEFT_UP;
    }
    private static final int GLFW_HAT_LEFT_DOWN = (int)12L;
    /**
     * {@snippet lang=c :
     * #define GLFW_HAT_LEFT_DOWN 12
     * }
     */
    public static int GLFW_HAT_LEFT_DOWN() {
        return GLFW_HAT_LEFT_DOWN;
    }
    private static final int GLFW_KEY_UNKNOWN = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define GLFW_KEY_UNKNOWN -1
     * }
     */
    public static int GLFW_KEY_UNKNOWN() {
        return GLFW_KEY_UNKNOWN;
    }
    private static final int GLFW_KEY_LAST = (int)348L;
    /**
     * {@snippet lang=c :
     * #define GLFW_KEY_LAST 348
     * }
     */
    public static int GLFW_KEY_LAST() {
        return GLFW_KEY_LAST;
    }
    private static final int GLFW_MOUSE_BUTTON_LAST = (int)7L;
    /**
     * {@snippet lang=c :
     * #define GLFW_MOUSE_BUTTON_LAST 7
     * }
     */
    public static int GLFW_MOUSE_BUTTON_LAST() {
        return GLFW_MOUSE_BUTTON_LAST;
    }
    private static final int GLFW_MOUSE_BUTTON_LEFT = (int)0L;
    /**
     * {@snippet lang=c :
     * #define GLFW_MOUSE_BUTTON_LEFT 0
     * }
     */
    public static int GLFW_MOUSE_BUTTON_LEFT() {
        return GLFW_MOUSE_BUTTON_LEFT;
    }
    private static final int GLFW_MOUSE_BUTTON_RIGHT = (int)1L;
    /**
     * {@snippet lang=c :
     * #define GLFW_MOUSE_BUTTON_RIGHT 1
     * }
     */
    public static int GLFW_MOUSE_BUTTON_RIGHT() {
        return GLFW_MOUSE_BUTTON_RIGHT;
    }
    private static final int GLFW_MOUSE_BUTTON_MIDDLE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define GLFW_MOUSE_BUTTON_MIDDLE 2
     * }
     */
    public static int GLFW_MOUSE_BUTTON_MIDDLE() {
        return GLFW_MOUSE_BUTTON_MIDDLE;
    }
    private static final int GLFW_JOYSTICK_LAST = (int)15L;
    /**
     * {@snippet lang=c :
     * #define GLFW_JOYSTICK_LAST 15
     * }
     */
    public static int GLFW_JOYSTICK_LAST() {
        return GLFW_JOYSTICK_LAST;
    }
    private static final int GLFW_GAMEPAD_BUTTON_LAST = (int)14L;
    /**
     * {@snippet lang=c :
     * #define GLFW_GAMEPAD_BUTTON_LAST 14
     * }
     */
    public static int GLFW_GAMEPAD_BUTTON_LAST() {
        return GLFW_GAMEPAD_BUTTON_LAST;
    }
    private static final int GLFW_GAMEPAD_BUTTON_CROSS = (int)0L;
    /**
     * {@snippet lang=c :
     * #define GLFW_GAMEPAD_BUTTON_CROSS 0
     * }
     */
    public static int GLFW_GAMEPAD_BUTTON_CROSS() {
        return GLFW_GAMEPAD_BUTTON_CROSS;
    }
    private static final int GLFW_GAMEPAD_BUTTON_CIRCLE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define GLFW_GAMEPAD_BUTTON_CIRCLE 1
     * }
     */
    public static int GLFW_GAMEPAD_BUTTON_CIRCLE() {
        return GLFW_GAMEPAD_BUTTON_CIRCLE;
    }
    private static final int GLFW_GAMEPAD_BUTTON_SQUARE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define GLFW_GAMEPAD_BUTTON_SQUARE 2
     * }
     */
    public static int GLFW_GAMEPAD_BUTTON_SQUARE() {
        return GLFW_GAMEPAD_BUTTON_SQUARE;
    }
    private static final int GLFW_GAMEPAD_BUTTON_TRIANGLE = (int)3L;
    /**
     * {@snippet lang=c :
     * #define GLFW_GAMEPAD_BUTTON_TRIANGLE 3
     * }
     */
    public static int GLFW_GAMEPAD_BUTTON_TRIANGLE() {
        return GLFW_GAMEPAD_BUTTON_TRIANGLE;
    }
    private static final int GLFW_GAMEPAD_AXIS_LAST = (int)5L;
    /**
     * {@snippet lang=c :
     * #define GLFW_GAMEPAD_AXIS_LAST 5
     * }
     */
    public static int GLFW_GAMEPAD_AXIS_LAST() {
        return GLFW_GAMEPAD_AXIS_LAST;
    }
    private static final int GLFW_OPENGL_DEBUG_CONTEXT = (int)139271L;
    /**
     * {@snippet lang=c :
     * #define GLFW_OPENGL_DEBUG_CONTEXT 139271
     * }
     */
    public static int GLFW_OPENGL_DEBUG_CONTEXT() {
        return GLFW_OPENGL_DEBUG_CONTEXT;
    }
    private static final int GLFW_ANY_POSITION = (int)2147483648L;
    /**
     * {@snippet lang=c :
     * #define GLFW_ANY_POSITION 2147483648
     * }
     */
    public static int GLFW_ANY_POSITION() {
        return GLFW_ANY_POSITION;
    }
    private static final int GLFW_HRESIZE_CURSOR = (int)221189L;
    /**
     * {@snippet lang=c :
     * #define GLFW_HRESIZE_CURSOR 221189
     * }
     */
    public static int GLFW_HRESIZE_CURSOR() {
        return GLFW_HRESIZE_CURSOR;
    }
    private static final int GLFW_VRESIZE_CURSOR = (int)221190L;
    /**
     * {@snippet lang=c :
     * #define GLFW_VRESIZE_CURSOR 221190
     * }
     */
    public static int GLFW_VRESIZE_CURSOR() {
        return GLFW_VRESIZE_CURSOR;
    }
    private static final int GLFW_HAND_CURSOR = (int)221188L;
    /**
     * {@snippet lang=c :
     * #define GLFW_HAND_CURSOR 221188
     * }
     */
    public static int GLFW_HAND_CURSOR() {
        return GLFW_HAND_CURSOR;
    }
    private static final int GLFW_DONT_CARE = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define GLFW_DONT_CARE -1
     * }
     */
    public static int GLFW_DONT_CARE() {
        return GLFW_DONT_CARE;
    }
}

