// Generated by jextract

package io.vacco.ujgl.gfx.rgfw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * union RGFW_event {
 *     RGFW_eventType type;
 *     RGFW_commonEvent common;
 *     RGFW_mouseButtonEvent button;
 *     RGFW_mouseScrollEvent scroll;
 *     RGFW_mousePosEvent mouse;
 *     RGFW_keyEvent key;
 *     RGFW_dataDropEvent drop;
 *     RGFW_dataDragEvent drag;
 *     RGFW_scaleUpdatedEvent scale;
 * }
 * }
 */
public class RGFW_event {

    RGFW_event() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
        rgfw_h.C_CHAR.withName("type"),
        RGFW_commonEvent.layout().withName("common"),
        RGFW_mouseButtonEvent.layout().withName("button"),
        RGFW_mouseScrollEvent.layout().withName("scroll"),
        RGFW_mousePosEvent.layout().withName("mouse"),
        RGFW_keyEvent.layout().withName("key"),
        RGFW_dataDropEvent.layout().withName("drop"),
        RGFW_dataDragEvent.layout().withName("drag"),
        RGFW_scaleUpdatedEvent.layout().withName("scale")
    ).withName("RGFW_event");

    /**
     * The layout of this union
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte type$LAYOUT = (OfByte)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * RGFW_eventType type
     * }
     */
    public static final OfByte type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * RGFW_eventType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * RGFW_eventType type
     * }
     */
    public static byte type(MemorySegment union) {
        return union.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * RGFW_eventType type
     * }
     */
    public static void type(MemorySegment union, byte fieldValue) {
        union.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final GroupLayout common$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("common"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * RGFW_commonEvent common
     * }
     */
    public static final GroupLayout common$layout() {
        return common$LAYOUT;
    }

    private static final long common$OFFSET = $LAYOUT.byteOffset(groupElement("common"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * RGFW_commonEvent common
     * }
     */
    public static final long common$offset() {
        return common$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * RGFW_commonEvent common
     * }
     */
    public static MemorySegment common(MemorySegment union) {
        return union.asSlice(common$OFFSET, common$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * RGFW_commonEvent common
     * }
     */
    public static void common(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, common$OFFSET, common$LAYOUT.byteSize());
    }

    private static final GroupLayout button$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("button"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * RGFW_mouseButtonEvent button
     * }
     */
    public static final GroupLayout button$layout() {
        return button$LAYOUT;
    }

    private static final long button$OFFSET = $LAYOUT.byteOffset(groupElement("button"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * RGFW_mouseButtonEvent button
     * }
     */
    public static final long button$offset() {
        return button$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * RGFW_mouseButtonEvent button
     * }
     */
    public static MemorySegment button(MemorySegment union) {
        return union.asSlice(button$OFFSET, button$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * RGFW_mouseButtonEvent button
     * }
     */
    public static void button(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, button$OFFSET, button$LAYOUT.byteSize());
    }

    private static final GroupLayout scroll$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("scroll"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * RGFW_mouseScrollEvent scroll
     * }
     */
    public static final GroupLayout scroll$layout() {
        return scroll$LAYOUT;
    }

    private static final long scroll$OFFSET = $LAYOUT.byteOffset(groupElement("scroll"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * RGFW_mouseScrollEvent scroll
     * }
     */
    public static final long scroll$offset() {
        return scroll$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * RGFW_mouseScrollEvent scroll
     * }
     */
    public static MemorySegment scroll(MemorySegment union) {
        return union.asSlice(scroll$OFFSET, scroll$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * RGFW_mouseScrollEvent scroll
     * }
     */
    public static void scroll(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, scroll$OFFSET, scroll$LAYOUT.byteSize());
    }

    private static final GroupLayout mouse$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("mouse"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * RGFW_mousePosEvent mouse
     * }
     */
    public static final GroupLayout mouse$layout() {
        return mouse$LAYOUT;
    }

    private static final long mouse$OFFSET = $LAYOUT.byteOffset(groupElement("mouse"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * RGFW_mousePosEvent mouse
     * }
     */
    public static final long mouse$offset() {
        return mouse$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * RGFW_mousePosEvent mouse
     * }
     */
    public static MemorySegment mouse(MemorySegment union) {
        return union.asSlice(mouse$OFFSET, mouse$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * RGFW_mousePosEvent mouse
     * }
     */
    public static void mouse(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, mouse$OFFSET, mouse$LAYOUT.byteSize());
    }

    private static final GroupLayout key$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("key"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * RGFW_keyEvent key
     * }
     */
    public static final GroupLayout key$layout() {
        return key$LAYOUT;
    }

    private static final long key$OFFSET = $LAYOUT.byteOffset(groupElement("key"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * RGFW_keyEvent key
     * }
     */
    public static final long key$offset() {
        return key$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * RGFW_keyEvent key
     * }
     */
    public static MemorySegment key(MemorySegment union) {
        return union.asSlice(key$OFFSET, key$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * RGFW_keyEvent key
     * }
     */
    public static void key(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, key$OFFSET, key$LAYOUT.byteSize());
    }

    private static final GroupLayout drop$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("drop"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * RGFW_dataDropEvent drop
     * }
     */
    public static final GroupLayout drop$layout() {
        return drop$LAYOUT;
    }

    private static final long drop$OFFSET = $LAYOUT.byteOffset(groupElement("drop"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * RGFW_dataDropEvent drop
     * }
     */
    public static final long drop$offset() {
        return drop$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * RGFW_dataDropEvent drop
     * }
     */
    public static MemorySegment drop(MemorySegment union) {
        return union.asSlice(drop$OFFSET, drop$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * RGFW_dataDropEvent drop
     * }
     */
    public static void drop(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, drop$OFFSET, drop$LAYOUT.byteSize());
    }

    private static final GroupLayout drag$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("drag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * RGFW_dataDragEvent drag
     * }
     */
    public static final GroupLayout drag$layout() {
        return drag$LAYOUT;
    }

    private static final long drag$OFFSET = $LAYOUT.byteOffset(groupElement("drag"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * RGFW_dataDragEvent drag
     * }
     */
    public static final long drag$offset() {
        return drag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * RGFW_dataDragEvent drag
     * }
     */
    public static MemorySegment drag(MemorySegment union) {
        return union.asSlice(drag$OFFSET, drag$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * RGFW_dataDragEvent drag
     * }
     */
    public static void drag(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, drag$OFFSET, drag$LAYOUT.byteSize());
    }

    private static final GroupLayout scale$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("scale"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * RGFW_scaleUpdatedEvent scale
     * }
     */
    public static final GroupLayout scale$layout() {
        return scale$LAYOUT;
    }

    private static final long scale$OFFSET = $LAYOUT.byteOffset(groupElement("scale"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * RGFW_scaleUpdatedEvent scale
     * }
     */
    public static final long scale$offset() {
        return scale$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * RGFW_scaleUpdatedEvent scale
     * }
     */
    public static MemorySegment scale(MemorySegment union) {
        return union.asSlice(scale$OFFSET, scale$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * RGFW_scaleUpdatedEvent scale
     * }
     */
    public static void scale(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, scale$OFFSET, scale$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this union
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

