// Generated by jextract

package io.vacco.ujgl.gfx.rgfw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*RGFW_keyfunc)(RGFW_window *, u8, u8, RGFW_keymod, RGFW_bool, RGFW_bool)
 * }
 */
public final class RGFW_keyfunc {

    private RGFW_keyfunc() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment win, byte key, byte sym, byte mod, byte repeat, byte pressed);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        rgfw_h.C_POINTER,
        rgfw_h.C_CHAR,
        rgfw_h.C_CHAR,
        rgfw_h.C_CHAR,
        rgfw_h.C_CHAR,
        rgfw_h.C_CHAR
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = rgfw_h.upcallHandle(RGFW_keyfunc.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(RGFW_keyfunc.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment win, byte key, byte sym, byte mod, byte repeat, byte pressed) {
        try {
             DOWN$MH.invokeExact(funcPtr, win, key, sym, mod, repeat, pressed);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

