// Generated by jextract

package io.vacco.ujgl.gfx.rgfw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct RGFW_monitor {
 *     i32 x;
 *     i32 y;
 *     char name[128];
 *     float scaleX;
 *     float scaleY;
 *     float pixelRatio;
 *     float physW;
 *     float physH;
 *     RGFW_monitorMode mode;
 * }
 * }
 */
public class RGFW_monitor {

    RGFW_monitor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        rgfw_h.C_INT.withName("x"),
        rgfw_h.C_INT.withName("y"),
        MemoryLayout.sequenceLayout(128, rgfw_h.C_CHAR).withName("name"),
        rgfw_h.C_FLOAT.withName("scaleX"),
        rgfw_h.C_FLOAT.withName("scaleY"),
        rgfw_h.C_FLOAT.withName("pixelRatio"),
        rgfw_h.C_FLOAT.withName("physW"),
        rgfw_h.C_FLOAT.withName("physH"),
        RGFW_monitorMode.layout().withName("mode")
    ).withName("RGFW_monitor");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt x$LAYOUT = (OfInt)$LAYOUT.select(groupElement("x"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * i32 x
     * }
     */
    public static final OfInt x$layout() {
        return x$LAYOUT;
    }

    private static final long x$OFFSET = $LAYOUT.byteOffset(groupElement("x"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * i32 x
     * }
     */
    public static final long x$offset() {
        return x$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * i32 x
     * }
     */
    public static int x(MemorySegment struct) {
        return struct.get(x$LAYOUT, x$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * i32 x
     * }
     */
    public static void x(MemorySegment struct, int fieldValue) {
        struct.set(x$LAYOUT, x$OFFSET, fieldValue);
    }

    private static final OfInt y$LAYOUT = (OfInt)$LAYOUT.select(groupElement("y"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * i32 y
     * }
     */
    public static final OfInt y$layout() {
        return y$LAYOUT;
    }

    private static final long y$OFFSET = $LAYOUT.byteOffset(groupElement("y"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * i32 y
     * }
     */
    public static final long y$offset() {
        return y$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * i32 y
     * }
     */
    public static int y(MemorySegment struct) {
        return struct.get(y$LAYOUT, y$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * i32 y
     * }
     */
    public static void y(MemorySegment struct, int fieldValue) {
        struct.set(y$LAYOUT, y$OFFSET, fieldValue);
    }

    private static final SequenceLayout name$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char name[128]
     * }
     */
    public static final SequenceLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = $LAYOUT.byteOffset(groupElement("name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char name[128]
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char name[128]
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.asSlice(name$OFFSET, name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char name[128]
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, name$OFFSET, name$LAYOUT.byteSize());
    }

    private static long[] name$DIMS = { 128 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char name[128]
     * }
     */
    public static long[] name$dimensions() {
        return name$DIMS;
    }
    private static final VarHandle name$ELEM_HANDLE = name$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char name[128]
     * }
     */
    public static byte name(MemorySegment struct, long index0) {
        return (byte)name$ELEM_HANDLE.get(struct, name$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char name[128]
     * }
     */
    public static void name(MemorySegment struct, long index0, byte fieldValue) {
        name$ELEM_HANDLE.set(struct, name$OFFSET, index0, fieldValue);
    }

    private static final OfFloat scaleX$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("scaleX"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float scaleX
     * }
     */
    public static final OfFloat scaleX$layout() {
        return scaleX$LAYOUT;
    }

    private static final long scaleX$OFFSET = $LAYOUT.byteOffset(groupElement("scaleX"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float scaleX
     * }
     */
    public static final long scaleX$offset() {
        return scaleX$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float scaleX
     * }
     */
    public static float scaleX(MemorySegment struct) {
        return struct.get(scaleX$LAYOUT, scaleX$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float scaleX
     * }
     */
    public static void scaleX(MemorySegment struct, float fieldValue) {
        struct.set(scaleX$LAYOUT, scaleX$OFFSET, fieldValue);
    }

    private static final OfFloat scaleY$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("scaleY"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float scaleY
     * }
     */
    public static final OfFloat scaleY$layout() {
        return scaleY$LAYOUT;
    }

    private static final long scaleY$OFFSET = $LAYOUT.byteOffset(groupElement("scaleY"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float scaleY
     * }
     */
    public static final long scaleY$offset() {
        return scaleY$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float scaleY
     * }
     */
    public static float scaleY(MemorySegment struct) {
        return struct.get(scaleY$LAYOUT, scaleY$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float scaleY
     * }
     */
    public static void scaleY(MemorySegment struct, float fieldValue) {
        struct.set(scaleY$LAYOUT, scaleY$OFFSET, fieldValue);
    }

    private static final OfFloat pixelRatio$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("pixelRatio"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float pixelRatio
     * }
     */
    public static final OfFloat pixelRatio$layout() {
        return pixelRatio$LAYOUT;
    }

    private static final long pixelRatio$OFFSET = $LAYOUT.byteOffset(groupElement("pixelRatio"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float pixelRatio
     * }
     */
    public static final long pixelRatio$offset() {
        return pixelRatio$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float pixelRatio
     * }
     */
    public static float pixelRatio(MemorySegment struct) {
        return struct.get(pixelRatio$LAYOUT, pixelRatio$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float pixelRatio
     * }
     */
    public static void pixelRatio(MemorySegment struct, float fieldValue) {
        struct.set(pixelRatio$LAYOUT, pixelRatio$OFFSET, fieldValue);
    }

    private static final OfFloat physW$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("physW"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float physW
     * }
     */
    public static final OfFloat physW$layout() {
        return physW$LAYOUT;
    }

    private static final long physW$OFFSET = $LAYOUT.byteOffset(groupElement("physW"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float physW
     * }
     */
    public static final long physW$offset() {
        return physW$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float physW
     * }
     */
    public static float physW(MemorySegment struct) {
        return struct.get(physW$LAYOUT, physW$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float physW
     * }
     */
    public static void physW(MemorySegment struct, float fieldValue) {
        struct.set(physW$LAYOUT, physW$OFFSET, fieldValue);
    }

    private static final OfFloat physH$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("physH"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float physH
     * }
     */
    public static final OfFloat physH$layout() {
        return physH$LAYOUT;
    }

    private static final long physH$OFFSET = $LAYOUT.byteOffset(groupElement("physH"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float physH
     * }
     */
    public static final long physH$offset() {
        return physH$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float physH
     * }
     */
    public static float physH(MemorySegment struct) {
        return struct.get(physH$LAYOUT, physH$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float physH
     * }
     */
    public static void physH(MemorySegment struct, float fieldValue) {
        struct.set(physH$LAYOUT, physH$OFFSET, fieldValue);
    }

    private static final GroupLayout mode$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("mode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * RGFW_monitorMode mode
     * }
     */
    public static final GroupLayout mode$layout() {
        return mode$LAYOUT;
    }

    private static final long mode$OFFSET = $LAYOUT.byteOffset(groupElement("mode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * RGFW_monitorMode mode
     * }
     */
    public static final long mode$offset() {
        return mode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * RGFW_monitorMode mode
     * }
     */
    public static MemorySegment mode(MemorySegment struct) {
        return struct.asSlice(mode$OFFSET, mode$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * RGFW_monitorMode mode
     * }
     */
    public static void mode(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, mode$OFFSET, mode$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

