// Generated by jextract

package io.vacco.ujgl.gfx.rgfw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct RGFW_monitorMode {
 *     i32 w;
 *     i32 h;
 *     u32 refreshRate;
 *     u8 red;
 *     u8 blue;
 *     u8 green;
 * }
 * }
 */
public class RGFW_monitorMode {

    RGFW_monitorMode() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        rgfw_h.C_INT.withName("w"),
        rgfw_h.C_INT.withName("h"),
        rgfw_h.C_INT.withName("refreshRate"),
        rgfw_h.C_CHAR.withName("red"),
        rgfw_h.C_CHAR.withName("blue"),
        rgfw_h.C_CHAR.withName("green"),
        MemoryLayout.paddingLayout(1)
    ).withName("RGFW_monitorMode");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt w$LAYOUT = (OfInt)$LAYOUT.select(groupElement("w"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * i32 w
     * }
     */
    public static final OfInt w$layout() {
        return w$LAYOUT;
    }

    private static final long w$OFFSET = $LAYOUT.byteOffset(groupElement("w"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * i32 w
     * }
     */
    public static final long w$offset() {
        return w$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * i32 w
     * }
     */
    public static int w(MemorySegment struct) {
        return struct.get(w$LAYOUT, w$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * i32 w
     * }
     */
    public static void w(MemorySegment struct, int fieldValue) {
        struct.set(w$LAYOUT, w$OFFSET, fieldValue);
    }

    private static final OfInt h$LAYOUT = (OfInt)$LAYOUT.select(groupElement("h"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * i32 h
     * }
     */
    public static final OfInt h$layout() {
        return h$LAYOUT;
    }

    private static final long h$OFFSET = $LAYOUT.byteOffset(groupElement("h"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * i32 h
     * }
     */
    public static final long h$offset() {
        return h$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * i32 h
     * }
     */
    public static int h(MemorySegment struct) {
        return struct.get(h$LAYOUT, h$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * i32 h
     * }
     */
    public static void h(MemorySegment struct, int fieldValue) {
        struct.set(h$LAYOUT, h$OFFSET, fieldValue);
    }

    private static final OfInt refreshRate$LAYOUT = (OfInt)$LAYOUT.select(groupElement("refreshRate"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * u32 refreshRate
     * }
     */
    public static final OfInt refreshRate$layout() {
        return refreshRate$LAYOUT;
    }

    private static final long refreshRate$OFFSET = $LAYOUT.byteOffset(groupElement("refreshRate"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * u32 refreshRate
     * }
     */
    public static final long refreshRate$offset() {
        return refreshRate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * u32 refreshRate
     * }
     */
    public static int refreshRate(MemorySegment struct) {
        return struct.get(refreshRate$LAYOUT, refreshRate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * u32 refreshRate
     * }
     */
    public static void refreshRate(MemorySegment struct, int fieldValue) {
        struct.set(refreshRate$LAYOUT, refreshRate$OFFSET, fieldValue);
    }

    private static final OfByte red$LAYOUT = (OfByte)$LAYOUT.select(groupElement("red"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * u8 red
     * }
     */
    public static final OfByte red$layout() {
        return red$LAYOUT;
    }

    private static final long red$OFFSET = $LAYOUT.byteOffset(groupElement("red"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * u8 red
     * }
     */
    public static final long red$offset() {
        return red$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * u8 red
     * }
     */
    public static byte red(MemorySegment struct) {
        return struct.get(red$LAYOUT, red$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * u8 red
     * }
     */
    public static void red(MemorySegment struct, byte fieldValue) {
        struct.set(red$LAYOUT, red$OFFSET, fieldValue);
    }

    private static final OfByte blue$LAYOUT = (OfByte)$LAYOUT.select(groupElement("blue"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * u8 blue
     * }
     */
    public static final OfByte blue$layout() {
        return blue$LAYOUT;
    }

    private static final long blue$OFFSET = $LAYOUT.byteOffset(groupElement("blue"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * u8 blue
     * }
     */
    public static final long blue$offset() {
        return blue$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * u8 blue
     * }
     */
    public static byte blue(MemorySegment struct) {
        return struct.get(blue$LAYOUT, blue$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * u8 blue
     * }
     */
    public static void blue(MemorySegment struct, byte fieldValue) {
        struct.set(blue$LAYOUT, blue$OFFSET, fieldValue);
    }

    private static final OfByte green$LAYOUT = (OfByte)$LAYOUT.select(groupElement("green"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * u8 green
     * }
     */
    public static final OfByte green$layout() {
        return green$LAYOUT;
    }

    private static final long green$OFFSET = $LAYOUT.byteOffset(groupElement("green"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * u8 green
     * }
     */
    public static final long green$offset() {
        return green$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * u8 green
     * }
     */
    public static byte green(MemorySegment struct) {
        return struct.get(green$LAYOUT, green$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * u8 green
     * }
     */
    public static void green(MemorySegment struct, byte fieldValue) {
        struct.set(green$LAYOUT, green$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

