// Generated by jextract

package io.vacco.ujgl.gfx.rgfw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct RGFW_dataDropEvent {
 *     RGFW_eventType type;
 *     RGFW_window *win;
 *     char **files;
 *     size_t count;
 * }
 * }
 */
public class RGFW_dataDropEvent {

    RGFW_dataDropEvent() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        rgfw_h.C_CHAR.withName("type"),
        MemoryLayout.paddingLayout(7),
        rgfw_h.C_POINTER.withName("win"),
        rgfw_h.C_POINTER.withName("files"),
        rgfw_h.C_LONG.withName("count")
    ).withName("RGFW_dataDropEvent");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte type$LAYOUT = (OfByte)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * RGFW_eventType type
     * }
     */
    public static final OfByte type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * RGFW_eventType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * RGFW_eventType type
     * }
     */
    public static byte type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * RGFW_eventType type
     * }
     */
    public static void type(MemorySegment struct, byte fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final AddressLayout win$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("win"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * RGFW_window *win
     * }
     */
    public static final AddressLayout win$layout() {
        return win$LAYOUT;
    }

    private static final long win$OFFSET = $LAYOUT.byteOffset(groupElement("win"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * RGFW_window *win
     * }
     */
    public static final long win$offset() {
        return win$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * RGFW_window *win
     * }
     */
    public static MemorySegment win(MemorySegment struct) {
        return struct.get(win$LAYOUT, win$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * RGFW_window *win
     * }
     */
    public static void win(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(win$LAYOUT, win$OFFSET, fieldValue);
    }

    private static final AddressLayout files$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("files"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char **files
     * }
     */
    public static final AddressLayout files$layout() {
        return files$LAYOUT;
    }

    private static final long files$OFFSET = $LAYOUT.byteOffset(groupElement("files"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char **files
     * }
     */
    public static final long files$offset() {
        return files$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char **files
     * }
     */
    public static MemorySegment files(MemorySegment struct) {
        return struct.get(files$LAYOUT, files$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char **files
     * }
     */
    public static void files(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(files$LAYOUT, files$OFFSET, fieldValue);
    }

    private static final OfLong count$LAYOUT = (OfLong)$LAYOUT.select(groupElement("count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t count
     * }
     */
    public static final OfLong count$layout() {
        return count$LAYOUT;
    }

    private static final long count$OFFSET = $LAYOUT.byteOffset(groupElement("count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t count
     * }
     */
    public static final long count$offset() {
        return count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t count
     * }
     */
    public static long count(MemorySegment struct) {
        return struct.get(count$LAYOUT, count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t count
     * }
     */
    public static void count(MemorySegment struct, long fieldValue) {
        struct.set(count$LAYOUT, count$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

